### PR TITLE
Model setup

### PR DESCRIPTION
**Pull request by KevinMCollier**
I tried to make all the models.

I think I got the columns correct, but not 100% about the associations in the models.
I tried my best lol

Someone please check if you can.

### CODE REVIEW

**Comment by KarasuGummi** [comment]
image

Are we planning on adding an 'image_url' column eventually down the line?

**Comment by KarasuGummi** [comment]
I think it would also be better to add a description column

**Comment by KarasuGummi** [comment]
the associations look good to me btw

**Comment by KevinMCollier** [comment]
Thanks curtis.

We will definitely need an image but I wasn't sure if it's done with active record or if we need to type it in?

I thought maybe with active record installed we could just put in the model that a buddy has_a :photo or something like that.

I'll double check

**Comment by KevinMCollier** [comment]
A description column definitely sounds good

**Comment by KarasuGummi** [comment]
do you want to update this branch with the description column? or should we make a new branch for it?

**Pull request merged**
